name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: env
      run: |
        echo env
        env
        echo is shell interactive
        [[ $- == *i* ]] && echo 'Interactive' || echo 'Not interactive'
