name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: env
      run: |
        echo which shell
        echo $-
        echo $0
        cat $0
        echo $SHELL
        echo env
        echo is shell interactive
        [[ $- == *i* ]] && echo 'Interactive' || echo 'Not interactive'
        env > /tmp/env.txt
    - uses: actions/upload-artifact@master
      with:
        name: env.txt
        path: /tmp/env.txt
    - name: sleep
      run: sleep 30
